# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Color Echo
email: khotta116@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://colorecho.github.io" # the base hostname & protocol for your site
url-gems: "https://rubygems.org/gems/color_echo"
url-github: "https://github.com/khotta/color_echo"
url-license: "https://github.com/khotta/color_echo/blob/master/LICENSE.txt"
url-download: "https://github.com/khotta/color_echo/tree/master/pkg"
#twitter_username: jekyllrb
github_username: khotta

# Build settings
markdown: kramdown

host: 0.0.0.0
port: 8080

description: >
    color_echo will work on Ruby 2.0.0 and over.

